//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerayis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gerayis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available..
        /// </summary>
        public static string AvailableUpdates {
            get {
                return ResourceManager.GetString("AvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Gerayis language..
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Gerayis theme..
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking updates on start is disabled..
        /// </summary>
        public static string CheckUpdatesDisabledOnStart {
            get {
                return ResourceManager.GetString("CheckUpdatesDisabledOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates on start.
        /// </summary>
        public static string CheckUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code11.
        /// </summary>
        public static string Code11 {
            get {
                return ResourceManager.GetString("Code11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code128.
        /// </summary>
        public static string Code128 {
            get {
                return ResourceManager.GetString("Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default bar code type.
        /// </summary>
        public static string DefaultBarCodeType {
            get {
                return ResourceManager.GetString("DefaultBarCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code:.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate bar code on start.
        /// </summary>
        public static string GenerateBarCodeOnStart {
            get {
                return ResourceManager.GetString("GenerateBarCodeOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR code on start.
        /// </summary>
        public static string GenerateQRCodeOnStart {
            get {
                return ResourceManager.GetString("GenerateQRCodeOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerayis.
        /// </summary>
        public static string Gerayis {
            get {
                return ResourceManager.GetString("Gerayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night.
        /// </summary>
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The history is empty..
        /// </summary>
        public static string HistoryEmpty {
            get {
                return ResourceManager.GetString("HistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install updates, Gerayis needs to restarts. Do you want to continue?.
        /// </summary>
        public static string InstallConfirmMsg {
            get {
                return ResourceManager.GetString("InstallConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install version.
        /// </summary>
        public static string InstallVersion {
            get {
                return ResourceManager.GetString("InstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSI.
        /// </summary>
        public static string MSI {
            get {
                return ResourceManager.GetString("MSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerayis needs to restart to apply the changes. Do you want to restart now?.
        /// </summary>
        public static string NeedRestartToApplyChanges {
            get {
                return ResourceManager.GetString("NeedRestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification when updates are available.
        /// </summary>
        public static string NotifyUpdates {
            get {
                return ResourceManager.GetString("NotifyUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use special characters..
        /// </summary>
        public static string NoUseSpecialChars {
            get {
                return ResourceManager.GetString("NoUseSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On start.
        /// </summary>
        public static string OnStart {
            get {
                return ResourceManager.GetString("OnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On start events..
        /// </summary>
        public static string OnStartDesc {
            get {
                return ResourceManager.GetString("OnStartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a correct value..
        /// </summary>
        public static string PleaseSpecifyValue {
            get {
                return ResourceManager.GetString("PleaseSpecifyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        public static string ResetColor {
            get {
                return ResourceManager.GetString("ResetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings?.
        /// </summary>
        public static string ResetSettingsConfirmMsg {
            get {
                return ResourceManager.GetString("ResetSettingsConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image has been sucessfully saved..
        /// </summary>
        public static string SaveSucess {
            get {
                return ResourceManager.GetString("SaveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See licenses.
        /// </summary>
        public static string SeeLicenses {
            get {
                return ResourceManager.GetString("SeeLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings exported sucessfully..
        /// </summary>
        public static string SettingsExportedSucessMsg {
            get {
                return ResourceManager.GetString("SettingsExportedSucessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been imported sucessfully. To finish the process, Gerayis will now restart..
        /// </summary>
        public static string SettingsImportedMsg {
            get {
                return ResourceManager.GetString("SettingsImportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings have been reset, Gerayis will now restart..
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bar code was successfully generated..
        /// </summary>
        public static string SuccessBarCodeGenerated {
            get {
                return ResourceManager.GetString("SuccessBarCodeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check updates.
        /// </summary>
        public static string UnableToCheckUpdates {
            get {
                return ResourceManager.GetString("UnableToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC-A.
        /// </summary>
        public static string UPCA {
            get {
                return ResourceManager.GetString("UPCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerayis is up to date..
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
