version: 2
updates:
- package-ecosystem: nuget
  directory: "/Gerayis"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: vNext
  reviewers:
  - Leo-Peyronnet
  assignees:
  - Leo-Peyronnet
  ignore:
  - dependency-name: LeoCorpLibrary
    versions:
    - 3.4.0.2103
